#+TITLE: My Site Configuration

* What is this?

  If you are reading this, I can only assume that is because you are
  me, and you are trying to change something about this site.  As
  such, hopefully most of this is all straight forward and still
  relevant.

* Org Settings

  For this website, we are not doing anything too fancy.  Just giving
  it a name

  #+BEGIN_SRC elisp
    (setq org-publish-project-alist
          '(("site"
             :base-directory "."
             :publishing-directory "."
             :base-extension "org"
             :publishing-function org-html-publish-to-html)))
  #+END_SRC

  #+RESULTS:
  | site | :base-directory | . | :publishing-directory | . | :base-extension | org | :publishing-function | org-html-publish-to-html |


  With that set, you can simply call [[elisp:(org-publish-current-project)]]

* Styling

** CSS Overrides

   Luckily, I don't actually have to do that much to get the site
   looking decently.  Actually, about the only thing I do is to limit
   the width to be about 50em.  I came to that number through some
   basic trial and error for what I thought looked decent.

   I also play with some of the alignments and hide the table of
   contents.

   #+BEGIN_SRC css :tangle org-overrides.css
     html {
       background: #020;
     }
     body {
       max-width: 50em;
       padding-left: 3em;
       padding-right: 3em;
       margin: auto;
       border: solid thin black;
       background-color: #DDD;
     }

     h1.title {
       text-align: left;
       padding: 1ex;
     }

     h1, h2, h3, h4 {
       margin-bottom: 1ex;
     }

     p {
       margin-top: 0;
     }

     div.outline-text-2, div.outline-text-3, div.outline-text-4 {
       padding: 1em;
       padding-top: 0;
     }
     .org-src-container {
       max-width: 40em;
       margin: auto;
     }
     .org-src-container .src {
       color: #EEE;
       background-color: #222;
       overflow: auto;
     }
     #table-of-contents {
       display: none;
     }

   #+END_SRC

** TODO Headers/Footers/etc

   I would like to get it so that headers and footers are all styled
   in a pleasant way.  Right now, I'm not even sure how to do that
   with org publishing, to be honest.

   I also am not sure I will be sticking with this stuff.  I hope I
   do... but I don't know if I will.
